version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '30230:5432'
    environment:
      - 'POSTGRES_PASSWORD='
      - POSTGRES_DB=online_shopping
    volumes:
      - db-var_lib_postgresql_data:/var/lib/postgresql/data

volumes:
  db-var_lib_postgresql_data:
